/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from Proto.Models.BroadcastMessage **/
    export interface BroadcastMessage {
        ConnectionId: string;
        Message: string;
        Added: string;
    }
}
